version: "3.8"
services:
  frontend:
    environment:
        - WDS_SOCKET_HOST=127.0.0.1 
        - CHOKIDAR_USEPOLLING=true
        - WATCHPACK_POLLING=true 
    build: ./frontend
    container_name: frontend
    ports:
      - '3000:3000'
    volumes:
    - ./frontend:/code
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: backend_c
    ports:
      - '3001:3001'
    stdin_open: true
    tty: true
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: rootpassword
      DB_NAME: dj_tool
    depends_on:
      - db

  db:
    image: mysql:latest
    container_name: mysql_c
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: dj_tool
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - '3306:3306'
    volumes:
      - db-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_c
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword
    depends_on:
      - db

volumes:
  db-data:
