const genreTags = {
    1: "House",
    2: "Techno",
    3: "Trance",
    4: "Dubstep",
    5: "Electro",
    6: "Ambient",
    7: "Chillout",
    8: "Drum and Bass",
    9: "Deep House",
    10: "Progressive House",
    11: "Minimal Techno",
    12: "Hardstyle",
    13: "Psytrance",
    14: "Electro House",
    15: "Future Bass",
    16: "Trap",
    17: "Tech House",
    18: "Big Room",
    19: "Breakbeat",
    20: "Synthwave",
    21: "Vaporwave",
    22: "Downtempo",
    23: "Electro Swing",
    24: "Hardcore",
    25: "Gabber",
    26: "IDM",
    27: "Future House",
    28: "Tropical House",
    29: "Acid House",
    30: "Jungle",
    31: "Liquid Drum and Bass",
    32: "Neurofunk",
    33: "UK Garage",
    34: "Speed Garage",
    35: "Ghetto House",
    36: "French House",
    37: "HipHop",
    38: "Rap",
    39: "Gangsta Rap",
    40: "Conscious Rap",
    41: "Boom Bap",
    42: "Drill",
    43: "Lo-fi Hip-Hop",
    44: "Grime",
    45: "Dark",
    46: "Happy",
    47: "Energetic",
    48: "Calm",
    49: "Melancholic",
    50: "Uplifting",
    51: "Romantic",
    52: "Sad",
    53: "Angry",
    54: "Relaxing",
    55: "Groovy",
    56: "Euphoric",
    57: "Dreamy",
    58: "Motivational",
    59: "Inspiring",
    60: "Mellow",
    61: "Chill",
    62: "Aggressive",
    63: "Peaceful",
    64: "Exciting",
    65: "Nostalgic",
    66: "Playful",
    67: "Soothing",
    68: "Reflective",
    69: "Hypnotic",
    70: "Mysterious",
    71: "Surreal",
    72: "Quirky",
    73: "Intense",
    74: "Melodic",
    75: "Heavy",
    76: "Light",
    77: "Bouncy",
    78: "Catchy",
    79: "Atmospheric",
    80: "Funky",
  };

  export const getGenreById = (id) => {
    if (id > 0 && id <= 80) {
      return genreTags[id];
    }
  };
  