name: 'coverage'

on:
  push:
    branches: [main]
  pull_request:
    branches:
      - master
      - main

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'  # Specify the Node.js version you are using

      - name: Install dependencies
        run: |
          cd frontend
          npm install

      - name: Run tests with coverage
        run: |
          cd frontend
          npm run test:ci  # Assuming this script runs the tests and generates the coverage report

      - name: Upload coverage report
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          working-directory: frontend
